### ISSUE TITLE
[Bug] Memory spikes during account management/user login

### ISSUE THREAD

**Issue by iKarTehFox** [luigi311/tanoshi#14]
Hello. I just spun up a container and tried to create the initial account in the web panel. It did not work, and the host system froze up.
I soon realized that whenever I press "Create Account", Tanoshi uses up all of the available memory allocated and eventually gets SIGKILL'ed by the OS. (The account is never created, and Tanoshi restarts as normal). No Docker logs are created during account creation.

I will clarify that my Docker environment is running on a system with _low memory_ (2GB). I have confirmed that this did not happen when I used the original image by faldez. ~~Does this new image use more memory?~~

### Edit:
**With further testing on the Windows client, I can see that memory usage spikes up to ~2GB (about 2,100MB ±50) when the first account is being created. The memory spikes also occur when the user logs in, and when creating more user accounts in the settings page.**

**Comment by luigi311** [comment]
Hmm i do see a spike when creating and logging in, i never noticed it since i usually just use it on unraid and i dont think the memory usage on it refreshes fast enough but i do see it when using the windows client. It seems to happen no matter what happens when a user logs in since it does it even if you put in an incorrect password so it atleast gives me a hint to look at.

**Comment by iKarTehFox** [comment]
> Hmm i do see a spike when creating and logging in, i never noticed it since i usually just use it on unraid and i dont think the memory usage on it refreshes fast enough but i do see it when using the windows client. It seems to happen no matter what happens when a user logs in since it does it even if you put in an incorrect password so it atleast gives me a hint to look at.
> 
> I just installed the faldez windows client and it looks like it also does it there so its not something new to my fork so thats good atleast.

Ah, you're right! However, what I can see while using Faldez's image, is that the Windows client has the same memory spikes, but **_not_** on the Docker container. When using **this repo's** image, both the Windows client and Docker container run into the same memory spiking problem. I really wonder what could be causing it; it's a very strange behavior.

**Comment by luigi311** [comment]
I think i found the issue, looks like its an issue with the fact that i increase the version of rust-argon2 from 1 to 2 and that is causing a big memory and cpu spike when it hashes and compares the password. I do see that faldez is using rust-argon2 so ill see if i can swap it over to the argon2 crate that is by the rustcrypto people and see if that also has the same issue but for now ill just revert back to version 1 and see what i find for the best solution.

**Comment by luigi311** [comment]
Looks like rust-argon2 switched the defaults around for v2 to follow the standard and be more secure instead of using the default settings from the C implementation they copied so its more cpu and memory intensive now which is what we might be seeing. Ill see if argon2 crate is faster at  handling  it and see what i do. I will still be reverting it for now until i decide what to do.

**Comment by luigi311** [comment]
Should be fixed by 172ee705f752bc3654e0e2b3bb95bafa926b59c6, rust-argon 2.X has swapped to more reasonable defaults
